spring:
  main:
    web-application-type: NONE
registrant:
  locale: "en"
  zone-id: "America/Sao_Paulo"
  google-cloud-platform:
    project-id: "register-272219"
    topic-id: "gmail_inbox_topic"
    subscription-id: "gmail_inbox_subscription"
    authorization:
      local-server-receiver-port: 8888
      authorized-user: "tw.breadware@gmail.com"
      tokens-directory-path: "tokens"
  messages:
    file-base-directory-path: "file:src/main/resources/i18n/messages"