spring:
  profiles:
    active:
      - "@spring.active-profile@"
  main:
    web-application-type: "NONE"
registrant:
  locale: "pt-BR"
  zone-id: "America/Sao_Paulo"
  messages:
    file-base-directory-path: "classpath:/i18n/messages"
  email:
    sender: "marcelo.leite@thoughtworks.com"
  google:
    cloud-platform:
      project-id: "register-272219"
      pub-sub:
        topic-id: "gmail_inbox_topic"
        subscription-id: "gmail_inbox_subscription"
      authorization:
        local-server-receiver-port: 8888
        authorized-user: "tw.breadware@gmail.com"
        tokens-storage-path: "gs://register-272219.appspot.com/authentication/tokens"
    sheets:
      spreadsheet-id: "1_SgDEroVR6XCavQCFe5GIfxVQvXA_DLfYgDfuodYpe8"
      sheet-name: "Dados"