spring:
  profiles:
    active:
      - "@spring.active-profile@"
  main:
    web-application-type: NONE
registrant:
  locale: "pt-BR"
  zone-id: "America/Sao_Paulo"
  email-verification-uuid: 862d8907-cbab-4434-b367-74ad89808300
  google-cloud-platform:
    project-id: "register-272219"
    topic-id: "gmail_inbox_topic"
    subscription-id: "gmail_inbox_subscription"
    authorization:
      local-server-receiver-port: 8888
      authorized-user: "tw.breadware@gmail.com"
      tokens-directory-path: "tokens"
  messages:
    file-base-directory-path: "classpath:/i18n/messages"