registrant:
  locale: "en"
  zone-id: "America/Sao_Paulo"
  messages:
    file-base-directory-path: "file:src/main/resources/i18n/messages"
  thymeleaf:
    cache: false
    template-prefix: "file:src/main/resources/thymeleaf/templates/"
