runtime: java11
instance_class: B1
manual_scaling:
  instances: 1

env_variables:
  JAVA_TOOL_OPTIONS: "-XX:MaxRAM=256m -XX:ActiveProcessorCount=2 -Xmx32m"
  APP_ENGINE_ENVIRONMENT: "true"
  GOOGLE_CLIENT_ID: "gs://register-272219.appspot.com/authentication/client-id-registrant.json"
